name: Terraform Azure VM Deployment

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.6.0

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Create Blob Container if not exists
      run: |
        az storage container create \
          --name tfstate \
          --account-name mytfstateaccount1 \
          --account-key ${{ secrets.STORAGE_ACCOUNT_KEY }} \
          --output none || true

    - name: Terraform Init
      run: terraform init

   # - name: Terraform Apply
   #   run: terraform apply -auto-approve

    # Optional: Detect and clean stale lock if apply fails
    - name: Check and Remove Stale Lock (Optional)
      if: failure()
      run: |
        echo "Checking for stale lock..."
        LOCK_EXISTS=$(az storage blob exists \
          --account-name mytfstateaccount1 \
          --account-key ${{ secrets.STORAGE_ACCOUNT_KEY }} \
          --container-name tfstate \
          --name .terraform.tfstate.lock.info \
          --query exists \
          --output tsv)

        - name: Terraform Apply
          run: terraform apply -auto-approve

        if [ "$LOCK_EXISTS" = "true" ]; then
          echo "Stale lock detected. Removing..."
          az storage blob delete \
            --account-name mytfstateaccount1 \
            --account-key ${{ secrets.STORAGE_ACCOUNT_KEY }} \
            --container-name tfstate \
            --name .terraform.tfstate.lock.info
        else
          echo "No stale lock found."
        fi
