name: Secondary Deployment


on:
  workflow_dispatch:


- name: Check for Lock
  id: check_lock
  run: |
    lease_status=$(az storage blob show \
      --container-name tfstate \
      --name terraform.tfstate \
      --account-name mytfstateaccount1 \
      --auth-mode login \
      --query "properties.lease.status" \
      --output tsv)
      

- name: Acquire Lease Lock
  id: acquire_lock
  run: |
    lease_id=$(az storage blob lease acquire \
      --container-name tfstate \
      --blob-name terraform.tfstate \
      --account-name mytfstateaccount1 \
      --auth-mode login \
      --duration infinite \
      --query leaseId -o tsv)
    echo "LEASE_ID=$lease_id" >> $GITHUB_ENV

- name: Terraform Apply
  run: terraform apply -auto-approve

- name: Release Lease Lock
  if: always()
  run: |
    az storage blob lease release \
      --container-name tfstate \
      --blob-name terraform.tfstate \
      --account-name mytfstateaccount1 \
      --auth-mode login \
      --lease-id $LEASE_ID
